### ISSUE TITLE
Zero ini

### ISSUE THREAD

**Issue by GasaiYU** [TheDenk/cogvideox-controlnet#18]
Thanks for you excellent work!

I wonder if there is anywhere zero-init in the controlnet, like the zero-conv original paper? Thanks!

**Comment by TheDenk** [comment]
Hey :)
No, I did not use it

**Comment by GasaiYU** [comment]
Thanks for your reply! Is it possible to make the training more stable and easier to converge if I add a zero-conv layer to the controlnet's output hidden states? 
In https://github.com/TheDenk/cogvideox-controlnet/blob/32153fc1c7709a5afa3a86aee75ae172e6a35379/cogvideo_controlnet.py#L217
to
`controlnet_hidden_states += (self.out_conv[i](hidden_states.permute(0,2,1)).permute(0,2,1),)`
where 
`self.out_conv = nn.ModuleList([zero_module(nn.Conv1d(inner_dim, inner_dim, 1, bias=False)) for _ in range(num_layers)])`
Thanks!

**Comment by TheDenk** [comment]
I tried it but did not see any difference :)
