### ISSUE TITLE
Prepare text embeds

### ISSUE THREAD

**Issue by alfredplpl** [TheDenk/cogvideox-controlnet#7]
I’m currently using ControlNet with additional training, but even with an H100 80GB GPU, the VRAM is insufficient. I believe this issue arises because the T5 encoder is too large. Currently, I’m running T5 on the CPU, which significantly slows down the process.

Would it be possible to implement an option to precompute the T5 encoder embeddings and use those during training? This could help alleviate VRAM requirements and speed up training. I’ve attached a relevant reference link below.
https://github.com/a-r-r-o-w/cogvideox-factory/blob/main/training/prepare_dataset.py

Thank you for considering this improvement!

**Comment by TheDenk** [comment]
@alfredplpl Hey :) It is strange because I trained controlnet for 2b model on A6000 (48GB), 49 frames and bs=1, fp16. And controlnet for 5b model on A100 (80GB), 41 frames and bs=1, bf16. What kind of model do you want to train?

**Comment by alfredplpl** [comment]
> What kind of model do you want to train?
Thanks for the response! I’m looking to train a ControlNet model using Canny with the 5B model. To clarify, I’m using eight H100 GPUs and want to train with Distributed Data Parallel (DDP).

Let me know if you have any recommendations for optimizing VRAM usage in this setup.

**Comment by TheDenk** [comment]
Sorry, but I did not train model with DDP, only with Accelerate :(

**Comment by alfredplpl** [comment]
However, I can run the T5 Encoder on CPU with normal speed.
We do not have to deal with this problem.
